import { useState, useEffect } from "react";
import { User } from "@supabase/supabase-js";

export const useFormData = (user: User | null) => {
  const [formData, setFormData] = useState({
    food: 0,
    oil: 0,
    steel: 0,
    mineral: 0,
    speed_up: 0,
    building_speed_up: 0,
    healing_speed_up: 0,
    recruitment_speed_up: 0,
    research_speed_up: 0,
    vip_level: 0,
    user_id_value: 0,
    nation: 0, // Changed to integer to match schema
    power_rank: 0,
    battle_power: 0,
    enemy_units_killed: 0,
    defense_victory: 0,
    siege_victory: 0,
    losses: 0,
    sieges_failed: 0,
    individual_reputation: 0,
    exp_current: 0,
    exp_total: 0,
    gas_current: 0,
    gas_total: 0,
    defense_against_biochemical_zombies_boost: 0,
    enemy_melee_attack_reduction: 0,
    enemy_mid_range_attack_reduction: 0,
    enemy_long_range_attack_reduction: 0,
    enemy_biochemical_zombie_attack_reduction: 0,
    enemy_melee_defense_reduction: 0,
    enemy_mid_range_defense_reduction: 0,
    enemy_long_range_defense_reduction: 0,
    enemy_biochemical_zombie_defense_reduction: 0,
    oil_boost: 0,
    oil_boost_bonus: 0,
    steel_boost: 0,
    steel_boost_bonus: 0,
    mineral_production: 0,
    mineral_production_bonus: 0,
    food_boost: 0,
    food_boost_bonus: 0,
    food_gather_bonus: 0,
    oil_gather_bonus: 0,
    steel_gather_bonus: 0,
    mineral_gather_bonus: 0,
    gold_gather_bonus: 0,
    building_speed_additional_bonus: 0,
    technology_research: 0,
    load_boost: 0,
    monster_attack_speed: 0,
    mobility_recovery: '',
    healing_speed: 0,
    increase_max_wounded_units: 0,
    increase_max_wounded_units_bonus: 0,
    vehicle_queue: 0,
    vehicle_queue_bonus: 0,
    fleet_troops_units_limit: 0,
    fleet_troops_units_limit_bonus: 0,
    cross_nation_battle_troops_expansion: 0,
    fleet_speed: 0,
    recruitment_speed_up_stat: 0,
    melee_attack: 0,
    melee_defense: 0,
    melee_hp: 0,
    mid_range_attack: 0,
    mid_range_defense: 0,
    mid_range_hp: 0,
    long_range_attack: 0,
    long_range_defense: 0,
    long_range_hp: 0,
    increases_damage_to_long_range_troops: 0,
    increases_damage_to_mid_range_troops: 0,
    increases_damage_to_melee_troops: 0,
    reduces_damage_taken_from_long_range_troops: 0,
    reduces_damage_taken_from_mid_range_troops: 0,
    reduces_damage_taken_from_melee_troops: 0,
    biochemical_zombies_recruit_speed_boost: 0,
    biochemical_materials_collection_rate_boost: 0,
    biochemical_zombies_attack_boost: 0,
    biochemical_zombies_hp_boost: 0,
    biochemical_zombies_defense_boost: 0,
    biochemical_materials_collection_boost: 0,
    biochemical_zombies_recruit_limit_boost: 0,
    biochemical_zombie_army_limit_boost: 0,
    biochemical_zombies_limit_boost: 0,
    all_troops_block: 0,
    all_troops_block_percentage: 0,
    all_troops_disruptor_resistance: 0,
    all_troops_disruptor_resistance_percentage: 0,
    all_troops_misfire_resistance: 0,
    all_troops_misfire_resistance_percentage: 0,
    cross_nation_battle_melee_attack: 0,
    cross_nation_battle_melee_defense: 0,
    cross_nation_battle_melee_hp: 0,
    cross_nation_battle_mid_range_attack: 0,
    cross_nation_battle_mid_range_defense: 0,
    cross_nation_battle_mid_range_hp: 0,
    cross_nation_battle_long_range_attack: 0,
    cross_nation_battle_long_range_defense: 0,
    cross_nation_battle_long_range_hp: 0,
    cross_nation_battle_biochemical_zombies_attack: 0,
    cross_nation_battle_biochemical_zombies_defense: 0,
    cross_nation_battle_biochemical_zombies_hp: 0,
    attack_against_melee_boost: 0,
    attack_against_mid_range_boost: 0,
    attack_against_long_range_boost: 0,
    attack_against_biochemical_zombies_boost: 0,
    defense_against_melee_boost: 0,
    defense_against_mid_range_boost: 0,
    defense_against_long_range_boost: 0,
    username: '',
  });
  const [fetchError, setFetchError] = useState<string | null>(null);

  useEffect(() => {
    if (user) {
      console.log("User object:", user);
      console.log("User ID:", user.id, "Length:", user.id.length);
      const fetchResources = async () => {
        try {
          const response = await fetch(`/api/get-resources?user_id=${user.id}`);
          if (!response.ok) {
            let errorData;
            try {
              errorData = await response.json();
            } catch (parseErr) {
              errorData = { error: "Failed to parse error response from API" };
            }
            console.error("API error:", {
              status: response.status,
              statusText: response.statusText,
              body: errorData,
            });
            const errorMessage = errorData.message || errorData.error || `Failed to fetch data: ${response.status} ${response.statusText}`;
            throw new Error(errorMessage);
          }
          const result = await response.json();
          console.log("Raw API response:", result);
          if (result.data) {
            console.log("API response:", { data: result.data });
            setFormData((prev) => ({
              ...prev,
              food: result.data.food || prev.food,
              oil: result.data.oil || prev.oil,
              steel: result.data.steel || prev.steel,
              mineral: result.data.mineral || prev.mineral,
              speed_up: result.data.speed_up || prev.speed_up,
              building_speed_up: result.data.building_speed_up || prev.building_speed_up,
              healing_speed_up: result.data.healing_speed_up || prev.healing_speed_up,
              recruitment_speed_up: result.data.recruitment_speed_up || prev.recruitment_speed_up,
              research_speed_up: result.data.research_speed_up || prev.research_speed_up,
              vip_level: result.data.vip_level || prev.vip_level,
              user_id_value: result.data.user_id_value || prev.user_id_value,
              nation: result.data.nation || prev.nation,
              power_rank: result.data.power_rank || prev.power_rank,
              battle_power: result.data.battle_power || prev.battle_power,
              enemy_units_killed: result.data.enemy_units_killed || prev.enemy_units_killed,
              defense_victory: result.data.defense_victory || prev.defense_victory,
              siege_victory: result.data.siege_victory || prev.siege_victory,
              losses: result.data.losses || prev.losses,
              sieges_failed: result.data.sieges_failed || prev.sieges_failed,
              individual_reputation: result.data.individual_reputation || prev.individual_reputation,
              exp_current: result.data.exp_current || prev.exp_current,
              exp_total: result.data.exp_total || prev.exp_total,
              gas_current: result.data.gas_current || prev.gas_current,
              gas_total: result.data.gas_total || prev.gas_total,
              defense_against_biochemical_zombies_boost: result.data.defense_against_biochemical_zombies_boost || prev.defense_against_biochemical_zombies_boost,
              enemy_melee_attack_reduction: result.data.enemy_melee_attack_reduction || prev.enemy_melee_attack_reduction,
              enemy_mid_range_attack_reduction: result.data.enemy_mid_range_attack_reduction || prev.enemy_mid_range_attack_reduction,
              enemy_long_range_attack_reduction: result.data.enemy_long_range_attack_reduction || prev.enemy_long_range_attack_reduction,
              enemy_biochemical_zombie_attack_reduction: result.data.enemy_biochemical_zombie_attack_reduction || prev.enemy_biochemical_zombie_attack_reduction,
              enemy_melee_defense_reduction: result.data.enemy_melee_defense_reduction || prev.enemy_melee_defense_reduction,
              enemy_mid_range_defense_reduction: result.data.enemy_mid_range_defense_reduction || prev.enemy_mid_range_defense_reduction,
              enemy_long_range_defense_reduction: result.data.enemy_long_range_defense_reduction || prev.enemy_long_range_defense_reduction,
              enemy_biochemical_zombie_defense_reduction: result.data.enemy_biochemical_zombie_defense_reduction || prev.enemy_biochemical_zombie_defense_reduction,
              oil_boost: result.data.oil_boost || prev.oil_boost,
              oil_boost_bonus: result.data.oil_boost_bonus || prev.oil_boost_bonus,
              steel_boost: result.data.steel_boost || prev.steel_boost,
              steel_boost_bonus: result.data.steel_boost_bonus || prev.steel_boost_bonus,
              mineral_production: result.data.mineral_production || prev.mineral_production,
              mineral_production_bonus: result.data.mineral_production_bonus || prev.mineral_production_bonus,
              food_boost: result.data.food_boost || prev.food_boost,
              food_boost_bonus: result.data.food_boost_bonus || prev.food_boost_bonus,
              food_gather_bonus: result.data.food_gather_bonus || prev.food_gather_bonus,
              oil_gather_bonus: result.data.oil_gather_bonus || prev.oil_gather_bonus,
              steel_gather_bonus: result.data.steel_gather_bonus || prev.steel_gather_bonus,
              mineral_gather_bonus: result.data.mineral_gather_bonus || prev.mineral_gather_bonus,
              gold_gather_bonus: result.data.gold_gather_bonus || prev.gold_gather_bonus,
              building_speed_additional_bonus: result.data.building_speed_additional_bonus || prev.building_speed_additional_bonus,
              technology_research: result.data.technology_research || prev.technology_research,
              load_boost: result.data.load_boost || prev.load_boost,
              monster_attack_speed: result.data.monster_attack_speed || prev.monster_attack_speed,
              mobility_recovery: result.data.mobility_recovery || prev.mobility_recovery,
              healing_speed: result.data.healing_speed || prev.healing_speed,
              increase_max_wounded_units: result.data.increase_max_wounded_units || prev.increase_max_wounded_units,
              increase_max_wounded_units_bonus: result.data.increase_max_wounded_units_bonus || prev.increase_max_wounded_units_bonus,
              vehicle_queue: result.data.vehicle_queue || prev.vehicle_queue,
              vehicle_queue_bonus: result.data.vehicle_queue_bonus || prev.vehicle_queue_bonus,
              fleet_troops_units_limit: result.data.fleet_troops_units_limit || prev.fleet_troops_units_limit,
              fleet_troops_units_limit_bonus: result.data.fleet_troops_units_limit_bonus || prev.fleet_troops_units_limit_bonus,
              cross_nation_battle_troops_expansion: result.data.cross_nation_battle_troops_expansion || prev.cross_nation_battle_troops_expansion,
              fleet_speed: result.data.fleet_speed || prev.fleet_speed,
              recruitment_speed_up_stat: result.data.recruitment_speed_up_stat || prev.recruitment_speed_up_stat,
              melee_attack: result.data.melee_attack || prev.melee_attack,
              melee_defense: result.data.melee_defense || prev.melee_defense,
              melee_hp: result.data.melee_hp || prev.melee_hp,
              mid_range_attack: result.data.mid_range_attack || prev.mid_range_attack,
              mid_range_defense: result.data.mid_range_defense || prev.mid_range_defense,
              mid_range_hp: result.data.mid_range_hp || prev.mid_range_hp,
              long_range_attack: result.data.long_range_attack || prev.long_range_attack,
              long_range_defense: result.data.long_range_defense || prev.long_range_defense,
              long_range_hp: result.data.long_range_hp || prev.long_range_hp,
              increases_damage_to_long_range_troops: result.data.increases_damage_to_long_range_troops || prev.increases_damage_to_long_range_troops,
              increases_damage_to_mid_range_troops: result.data.increases_damage_to_mid_range_troops || prev.increases_damage_to_mid_range_troops,
              increases_damage_to_melee_troops: result.data.increases_damage_to_melee_troops || prev.increases_damage_to_melee_troops,
              reduces_damage_taken_from_long_range_troops: result.data.reduces_damage_taken_from_long_range_troops || prev.reduces_damage_taken_from_long_range_troops,
              reduces_damage_taken_from_mid_range_troops: result.data.reduces_damage_taken_from_mid_range_troops || prev.reduces_damage_taken_from_mid_range_troops,
              reduces_damage_taken_from_melee_troops: result.data.reduces_damage_taken_from_melee_troops || prev.reduces_damage_taken_from_melee_troops,
              biochemical_zombies_recruit_speed_boost: result.data.biochemical_zombies_recruit_speed_boost || prev.biochemical_zombies_recruit_speed_boost,
              biochemical_materials_collection_rate_boost: result.data.biochemical_materials_collection_rate_boost || prev.biochemical_materials_collection_rate_boost,
              biochemical_zombies_attack_boost: result.data.biochemical_zombies_attack_boost || prev.biochemical_zombies_attack_boost,
              biochemical_zombies_hp_boost: result.data.biochemical_zombies_hp_boost || prev.biochemical_zombies_hp_boost,
              biochemical_zombies_defense_boost: result.data.biochemical_zombies_defense_boost || prev.biochemical_zombies_defense_boost,
              biochemical_materials_collection_boost: result.data.biochemical_materials_collection_boost || prev.biochemical_materials_collection_boost,
              biochemical_zombies_recruit_limit_boost: result.data.biochemical_zombies_recruit_limit_boost || prev.biochemical_zombies_recruit_limit_boost,
              biochemical_zombie_army_limit_boost: result.data.biochemical_zombie_army_limit_boost || prev.biochemical_zombie_army_limit_boost,
              biochemical_zombies_limit_boost: result.data.biochemical_zombies_limit_boost || prev.biochemical_zombies_limit_boost,
              all_troops_block: result.data.all_troops_block || prev.all_troops_block,
              all_troops_block_percentage: result.data.all_troops_block_percentage || prev.all_troops_block_percentage,
              all_troops_disruptor_resistance: result.data.all_troops_disruptor_resistance || prev.all_troops_disruptor_resistance,
              all_troops_disruptor_resistance_percentage: result.data.all_troops_disruptor_resistance_percentage || prev.all_troops_disruptor_resistance_percentage,
              all_troops_misfire_resistance: result.data.all_troops_misfire_resistance || prev.all_troops_misfire_resistance,
              all_troops_misfire_resistance_percentage: result.data.all_troops_misfire_resistance_percentage || prev.all_troops_misfire_resistance_percentage,
              cross_nation_battle_melee_attack: result.data.cross_nation_battle_melee_attack || prev.cross_nation_battle_melee_attack,
              cross_nation_battle_melee_defense: result.data.cross_nation_battle_melee_defense || prev.cross_nation_battle_melee_defense,
              cross_nation_battle_melee_hp: result.data.cross_nation_battle_melee_hp || prev.cross_nation_battle_melee_hp,
              cross_nation_battle_mid_range_attack: result.data.cross_nation_battle_mid_range_attack || prev.cross_nation_battle_mid_range_attack,
              cross_nation_battle_mid_range_defense: result.data.cross_nation_battle_mid_range_defense || prev.cross_nation_battle_mid_range_defense,
              cross_nation_battle_mid_range_hp: result.data.cross_nation_battle_mid_range_hp || prev.cross_nation_battle_mid_range_hp,
              cross_nation_battle_long_range_attack: result.data.cross_nation_battle_long_range_attack || prev.cross_nation_battle_long_range_attack,
              cross_nation_battle_long_range_defense: result.data.cross_nation_battle_long_range_defense || prev.cross_nation_battle_long_range_defense,
              cross_nation_battle_long_range_hp: result.data.cross_nation_battle_long_range_hp || prev.cross_nation_battle_long_range_hp,
              cross_nation_battle_biochemical_zombies_attack: result.data.cross_nation_battle_biochemical_zombies_attack || prev.cross_nation_battle_biochemical_zombies_attack,
              cross_nation_battle_biochemical_zombies_defense: result.data.cross_nation_battle_biochemical_zombies_defense || prev.cross_nation_battle_biochemical_zombies_defense,
              cross_nation_battle_biochemical_zombies_hp: result.data.cross_nation_battle_biochemical_zombies_hp || prev.cross_nation_battle_biochemical_zombies_hp,
              attack_against_melee_boost: result.data.attack_against_melee_boost || prev.attack_against_melee_boost,
              attack_against_mid_range_boost: result.data.attack_against_mid_range_boost || prev.attack_against_mid_range_boost,
              attack_against_long_range_boost: result.data.attack_against_long_range_boost || prev.attack_against_long_range_boost,
              attack_against_biochemical_zombies_boost: result.data.attack_against_biochemical_zombies_boost || prev.attack_against_biochemical_zombies_boost,
              defense_against_melee_boost: result.data.defense_against_melee_boost || prev.defense_against_melee_boost,
              defense_against_mid_range_boost: result.data.defense_against_mid_range_boost || prev.defense_against_mid_range_boost,
              defense_against_long_range_boost: result.data.defense_against_long_range_boost || prev.defense_against_long_range_boost,
              username: result.data.username || prev.username,
            }));
          } else {
            console.log("No data found for user_id:", user.id);
          }
        } catch (error: any) {
          console.error("Fetch error:", error.message);
          setFetchError(`Failed to load data: ${error.message}`);
        }
      };
      fetchResources();
    }
  }, [user]);

  return { formData, setFormData, fetchError };
};